package drools.spring.rules

import ftn.bsep9.model.Log;

declare MultipleWarningsEvent
    @role(event)
    macAddress: String
end

rule "3 same warnings in 5 minutes"
    when
        // $log1: Log( $severity: severityType, $trackedMacAddress: MACAddress )
        $log1: Log(severityType.equals("WARNING"), $trackedMacAddress: MACAddress)
        Number(intValue >= 3) from accumulate(
            $log2: Log(
                text == $log1.getText(),        // same
                severityType.equals("WARNING"), // warnings
                MACAddress.equals($trackedMacAddress),
                this meets[5m] $log1
            ),
            count($log2)
        )
        // TODO: zapamtiti $severity da mozemo pratiti vise tipova severity-a jednim pravilom! :)
        // not (MultipleWarningsEvent(macAddress == $trackedMacAddress, severityType == $severity))
        not (MultipleWarningsEvent(macAddress == $trackedMacAddress))
    then
        insert(new MultipleWarningsEvent($trackedMacAddress));
        System.out.println("3 warnings on machine: " + $trackedMacAddress);
end