package drools.spring.rules;
dialect  "mvel"

import ftn.bsep9.model.Log;
import java.util.Date;

declare fiveOrMoreSameUsernameWarningsEvent
    @role(event)
    macAddress: String
    occuredAt: Date
    warningCount: int
    // TODO: memorize each warning's timestamp in order to have more than
    //       one MultipleWarningsEvent event per machine (MACAddress)
end

// by importing a STATIC function: // import function my.package.Foo.hello
function String getUsername(String text) {
    return text.substring(text.indexOf("User") + 5).split(" ", 2)[0];
}

function boolean noMoreThanXMinutesApart(int minutes, Date d) {
    return ((new Date()).getTime() - d.getTime()) <= minutes * 60 * 1000;
//    System.out.println("noMoreThanXMinutesApart: " + new Date());
}

rule "5+ same-username warnings in 5 minutes"
    when
        // $log1: Log( $severity: severityType, $trackedMacAddress: MACAddress )
        $log1: Log(severityType.equals("WARNING"), $trackedMacAddress: MACAddress)
        $warningsCount: Number(intValue >= 4) from accumulate(
            $log2: Log(
                this != $log1,
                getUsername(text).equals(getUsername($log1.getText())), // dodati i da su im tekstovi !=  ???
                severityType.equals("WARNING"),
                MACAddress.equals($trackedMacAddress),
                this meets[5m] $log1
            ),
            count($log2)
        )
        // TODO: zapamtiti $severity da mozemo pratiti vise tipova severity-a jednim pravilom! :)
        // not (fiveOrMoreSameUsernameWarningsEvent( ... ,  severityType == $severity ))
        not (fiveOrMoreSameUsernameWarningsEvent(noMoreThanXMinutesApart(5, occuredAt))) // macAddress == $trackedMacAddress,
    then
        System.out.println("Warnings count: " + $warningsCount.intValue() + "<- +1 !");
        System.out.println("ADD IT TO CONSTRUCTOR OF THIS EVENT!!!\n");
        insert(new fiveOrMoreSameUsernameWarningsEvent($trackedMacAddress, new Date(), $warningsCount + 1));
        System.out.println("5 same-username warnings in 5 minutes on machine: " + $trackedMacAddress);
end
