//created on: May 9, 2017
package drools.spring.rules

import ftn.bsep9.model.Log;

declare MultipleWarningsEvent
    @role(event)
    macAddress: String
end

declare AlarmTriggered
    macAddress: Long
end

rule "Alarm when 5 Warnings in 1 hour"
    when
        $log1: Log( severityType.equals("WARNING"), $trackedMacAddress: MACAddress )
        Number(intValue >= 5) from accumulate(
            $log2: TransactionEvent(
                this != $log1,
                macAddress.equals($trackedMacAddress), //  == is OK?
                this meets[1h] $log1 // meets[15m] !!!
            ),
            count($t2)
        )
        not (MultipleWarningsEvent(macAddress == $trackedMacAddress))
        // dodaj:  severityType == "NEKI_TIP"  da mozemo pratiti vise tipova severity-a jednim pravilom! :)
    then
        System.out.println("5 warnings on machine: " + $trackedMacAddress);
end

rule "Alarm for a Warning"
    when
        $log: Log( severityType.equals("WARNING") )
    then
        System.out.println("A warning! " + $log.getText());
end